### ISSUE TITLE
The menu sometimes undoes your changes before clicking apply

### ISSUE THREAD

**Issue by EatingSilencer** [Tslat/Worldgen-Visualizer#2]
When you make some changes to the world gen, sometimes going to apply said changes will reveal that the game has undid all the things you changed in the menu, forcing you to redo them.

**Comment by Tslat** [comment]
This is due to clicking the back button before unfocussing the field. This should be fixed in this commit:

https://github.com/Tslat/Worldgen-Visualizer/commit/74f48f301b51b730a421192d84ae395cf1b8e5a2#diff-67e6a3718c8c41cdf9cbfe68a2eab67dd1d41048ceb206f0dcfb87faadfe1981
